/**
 * 日记自动生成调度器
 * 监听游戏时间变化，自动为角色生成日记
 */

import { generateDiary } from './diaryGenerator';
import {
  saveDiary,
  getDiaryMeta,
  shouldAutoGenerateDiary,
  updateLastGeneratedDate,
  getDiaryGlobalSettings,
  updateLastCheckedDate,
  type DiaryEntry,
} from './diaryIndexedDb';
import { loadCharacterArchive, type PhoneCharacterArchive } from './characterArchive/bridge';
import { subscribeGameDateChange } from './tavernPhoneBridge';
import { getTaskManager } from './components/BackgroundTaskManager';

/** 当前游戏日期缓存 */
let currentGameDate: string | null = null;

/** 正在生成的角色集合（防止重复生成） */
const generatingSet = new Set<string>();

/** 手动触发回调列表 */
const manualTriggerCallbacks: Array<(entries: DiaryEntry[]) => void> = [];

/**
 * 从 MVU 变量中获取当前游戏日期
 * 通过请求上下文或从 window 对象获取
 */
export async function fetchCurrentGameDate(): Promise<string | null> {
  try {
    // 尝试从 window 对象获取（壳脚本会注入）
    const w = window as unknown as Record<string, unknown>;
    const dateFromWindow = w.__GAME_DATE__ || w.__CURRENT_GAME_DATE__;
    if (typeof dateFromWindow === 'string' && dateFromWindow) {
      return dateFromWindow;
    }

    // 尝试从上下文获取
    const ctx = await import('./tavernPhoneBridge').then(m => m.requestTavernPhoneContext());
    if (ctx?.recentStorySnippet) {
      // 尝试从剧情摘要中解析日期
      const dateMatch = ctx.recentStorySnippet.match(/(\d{4}[-/年]\d{1,2}[-/月]\d{1,2}[日]?)/);
      if (dateMatch) {
        return normalizeDate(dateMatch[1]);
      }
    }

    // 默认使用现实日期
    return formatDate(new Date());
  } catch (e) {
    console.warn('[diaryScheduler] 获取游戏日期失败:', e);
    return formatDate(new Date());
  }
}

/**
 * 格式化日期为统一格式 YYYY-MM-DD
 */
function formatDate(date: Date): string {
  const year = date.getFullYear();
  const month = String(date.getMonth() + 1).padStart(2, '0');
  const day = String(date.getDate()).padStart(2, '0');
  return `${year}-${month}-${day}`;
}

/**
 * 规范化各种日期格式为 YYYY-MM-DD
 */
function normalizeDate(dateStr: string): string {
  // 去除多余字符
  const cleaned = dateStr.replace(/[年月日/-]/g, '-').replace(/-+/g, '-').trim();
  const parts = cleaned.split('-').filter(Boolean);
  if (parts.length >= 3) {
    const year = parts[0];
    const month = String(parseInt(parts[1], 10)).padStart(2, '0');
    const day = String(parseInt(parts[2], 10)).padStart(2, '0');
    return `${year}-${month}-${day}`;
  }
  return formatDate(new Date());
}

/**
 * 解析日期字符串为 Date 对象
 */
function parseGameDate(dateStr: string): Date | null {
  const match = dateStr.match(/(\d{4})-(\d{2})-(\d{2})/);
  if (!match) return null;
  const [, year, month, day] = match;
  return new Date(parseInt(year), parseInt(month) - 1, parseInt(day));
}

/**
 * 计算两个游戏日期之间的天数差
 */
function getDaysBetween(date1: string, date2: string): number {
  const d1 = parseGameDate(date1);
  const d2 = parseGameDate(date2);
  if (!d1 || !d2) return 0;
  const msPerDay = 24 * 60 * 60 * 1000;
  return Math.floor((d2.getTime() - d1.getTime()) / msPerDay);
}

/**
 * 检查并自动生成日记
 * 支持按天数间隔自动生成
 */
export async function checkAndAutoGenerateDiaries(
  newGameDate: string,
): Promise<DiaryEntry[]> {
  // 更新当前游戏日期
  currentGameDate = newGameDate;

  // 获取全局设置
  const settings = await getDiaryGlobalSettings();

  // 如果自动更新未启用，直接返回
  if (!settings.autoUpdateEnabled) {
    return [];
  }

  const generatedEntries: DiaryEntry[] = [];

  try {
    // 计算距离上次检查过去了多少天
    const daysSinceLastCheck = settings.lastCheckedGameDate
      ? getDaysBetween(settings.lastCheckedGameDate, newGameDate)
      : Infinity; // 首次启用时立即生成

    // 如果未达到间隔天数，不生成
    if (daysSinceLastCheck < settings.intervalDays) {
      console.log(`[diaryScheduler] 距离上次生成还有 ${settings.intervalDays - daysSinceLastCheck} 天`);
      return [];
    }

    // 获取所有角色
    const characters = await loadCharacterArchive();
    if (!characters.length) {
      console.log('[diaryScheduler] 没有可生成日记的角色');
      return [];
    }

    console.log(`[diaryScheduler] 间隔 ${settings.intervalDays} 天触发，检查 ${characters.length} 个角色...`);

    // 检查每个角色
    for (const character of characters) {
      if (character.status !== '出场中') {
        continue;
      }

      const shouldGenerate = await shouldAutoGenerateDiary(character.id, newGameDate);
      if (!shouldGenerate) {
        continue;
      }

      // 防止重复生成
      if (generatingSet.has(character.id)) {
        continue;
      }
      generatingSet.add(character.id);

      try {
        // 生成日记
        const generated = await generateDiary({
          characterId: character.id,
          characterName: character.name,
          gameDate: newGameDate,
        });

        if (generated) {
          // 保存到数据库
          const entry = await saveDiary({
            characterId: character.id,
            characterName: character.name,
            gameDate: newGameDate,
            title: generated.title,
            content: generated.content,
            moodTags: generated.moodTags,
            isRead: false,
          });

          generatedEntries.push(entry);
          console.log(`[diaryScheduler] ✅ 已为 ${character.name} 生成日记: ${generated.title}`);

          // 更新元数据
          await updateLastGeneratedDate(character.id, newGameDate);
        }
      } catch (e) {
        console.error(`[diaryScheduler] 为 ${character.name} 生成日记失败:`, e);
      } finally {
        generatingSet.delete(character.id);
      }
    }

    // 更新最后检查日期
    await updateLastCheckedDate(newGameDate);

    // 通知回调
    if (generatedEntries.length > 0) {
      manualTriggerCallbacks.forEach(cb => cb(generatedEntries));
    }

    return generatedEntries;

  } catch (e) {
    console.error('[diaryScheduler] 自动检查日记生成失败:', e);
    return [];
  }
}

/**
 * 手动为指定角色生成日记（立即生成）
 */
export async function manualGenerateDiary(
  characterId: string,
  characterName: string,
  todayEvents?: string,
): Promise<DiaryEntry | null> {
  const gameDate = currentGameDate || (await fetchCurrentGameDate()) || formatDate(new Date());

  try {
    const generated = await generateDiary({
      characterId,
      characterName,
      gameDate,
      todayEvents,
    });

    if (!generated) {
      return null;
    }

    // 保存到数据库
    const entry = await saveDiary({
      characterId,
      characterName,
      gameDate,
      title: generated.title,
      content: generated.content,
      moodTags: generated.moodTags,
      isRead: false,
    });

    // 更新元数据
    await updateLastGeneratedDate(characterId, gameDate);

    console.log(`[diaryScheduler] ✅ 手动生成日记成功: ${entry.title}`);
    return entry;

  } catch (e) {
    console.error('[diaryScheduler] 手动生成日记失败:', e);
    return null;
  }
}

/**
 * 批量手动生成日记（为所有出场中的角色）
 */
export async function batchManualGenerateDiaries(
  todayEvents?: string,
  onProgress?: (current: number, total: number, name: string, success: boolean) => void,
): Promise<DiaryEntry[]> {
  const gameDate = currentGameDate || (await fetchCurrentGameDate()) || formatDate(new Date());
  const entries: DiaryEntry[] = [];

  try {
    const characters = await loadCharacterArchive();
    const activeCharacters = characters.filter(c => c.status === '出场中');

    if (!activeCharacters.length) {
      console.log('[diaryScheduler] 没有出场中的角色可生成日记');
      return [];
    }

    for (let i = 0; i < activeCharacters.length; i++) {
      const character = activeCharacters[i];

      const entry = await manualGenerateDiary(
        character.id,
        character.name,
        todayEvents,
      );

      const success = !!entry;
      if (entry) {
        entries.push(entry);
      }

      onProgress?.(i + 1, activeCharacters.length, character.name, success);
    }

    return entries;

  } catch (e) {
    console.error('[diaryScheduler] 批量生成日记失败:', e);
    return [];
  }
}

/**
 * 设置当前游戏日期（通常由壳脚本或外部调用）
 */
export function setCurrentGameDate(date: string): void {
  currentGameDate = date;
  console.log('[diaryScheduler] 游戏日期更新为:', date);
}

/**
 * 获取当前游戏日期
 */
export function getCurrentGameDate(): string | null {
  return currentGameDate;
}

/**
 * 订阅新日记生成事件
 */
export function onNewDiariesGenerated(callback: (entries: DiaryEntry[]) => void): () => void {
  manualTriggerCallbacks.push(callback);
  return () => {
    const idx = manualTriggerCallbacks.indexOf(callback);
    if (idx > -1) manualTriggerCallbacks.splice(idx, 1);
  };
}

/**
 * 后台批量生成日记
 * 使用任务管理器在后台执行，支持进度追踪
 */
export async function backgroundBatchGenerateDiaries(
  options: {
    characterIds?: string[];
    todayEvents?: string;
  },
  onComplete?: (entries: DiaryEntry[]) => void,
): Promise<string> {
  const taskManager = getTaskManager();
  const gameDate = currentGameDate || (await fetchCurrentGameDate()) || new Date().toISOString().split('T')[0];

  const { characterIds = [], todayEvents } = options;

  // 如果没有指定角色，获取所有出场中的角色
  let targetChars: PhoneCharacterArchive[] = [];
  if (characterIds.length > 0) {
    const allChars = await loadCharacterArchive();
    targetChars = allChars.filter(c => characterIds.includes(c.id) && c.status === '出场中');
  } else {
    const allChars = await loadCharacterArchive();
    targetChars = allChars.filter(c => c.status === '出场中');
  }

  if (targetChars.length === 0) {
    throw new Error('没有可生成日记的角色');
  }

  // 添加任务
  const taskId = taskManager.addTask({
    type: 'diary_generation',
    name: `生成${targetChars.length}个角色的日记`,
    progress: 0,
    current: 0,
    total: targetChars.length,
  });

  // 在后台执行
  setTimeout(async () => {
    taskManager.updateTask(taskId, { status: 'running' });
    const newEntries: DiaryEntry[] = [];

    for (let i = 0; i < targetChars.length; i++) {
      const character = targetChars[i];

      try {
        taskManager.updateTask(taskId, {
          name: `生成日记: ${character.name}`,
        });

        const generated = await generateDiary({
          characterId: character.id,
          characterName: character.name,
          gameDate,
          todayEvents,
        });

        if (generated) {
          // 保存到数据库
          const entry = await saveDiary({
            characterId: character.id,
            characterName: character.name,
            gameDate,
            title: generated.title,
            content: generated.content,
            moodTags: generated.moodTags,
            isRead: false,
          });

          // 更新元数据
          await updateLastGeneratedDate(character.id, gameDate);

          newEntries.push(entry);
          console.log(`[backgroundDiary] ✅ 日记生成成功: ${entry.title}`);
        }
      } catch (e) {
        console.error(`[backgroundDiary] 生成日记失败:`, e);
      }

      taskManager.setTaskProgress(taskId, i + 1, targetChars.length);
    }

    if (newEntries.length > 0) {
      taskManager.completeTask(taskId);
      onComplete?.(newEntries);
      // 触发回调通知UI刷新
      manualTriggerCallbacks.forEach(cb => cb(newEntries));
    } else {
      taskManager.errorTask(taskId, '没有成功生成任何日记');
    }
  }, 0);

  return taskId;
}

/**
 * 初始化调度器
 * 启动定时检查（每30秒检查一次日期变化）并订阅游戏日期推送
 */
export function initDiaryScheduler(): () => void {
  // 初始获取日期
  fetchCurrentGameDate().then(date => {
    if (date) {
      currentGameDate = date;
    }
  });

  // 订阅壳脚本推送的游戏日期变化
  const unsubscribeGameDate = subscribeGameDateChange(newDate => {
    if (newDate && newDate !== currentGameDate) {
      console.log('[diaryScheduler] 壳脚本推送日期变化:', currentGameDate, '->', newDate);
      void checkAndAutoGenerateDiaries(newDate);
    }
  });

  // 定期检查日期变化（作为备用机制）
  const intervalId = window.setInterval(async () => {
    const newDate = await fetchCurrentGameDate();
    if (newDate && newDate !== currentGameDate) {
      console.log('[diaryScheduler] 检测到日期变化:', currentGameDate, '->', newDate);
      await checkAndAutoGenerateDiaries(newDate);
    }
  }, 30000); // 每30秒检查一次

  return () => {
    clearInterval(intervalId);
    unsubscribeGameDate();
  };
}
