/** 与 React 版 AVAILABLE_ICONS 键名一致，值为 Font Awesome class */
export const ICON_MAP: Record<string, string> = {
  Mountain: 'fa-solid fa-mountain',
  Trees: 'fa-solid fa-tree',
  Castle: 'fa-solid fa-chess-rook',
  Tent: 'fa-solid fa-campground',
  Factory: 'fa-solid fa-industry',
  Building2: 'fa-solid fa-building',
  Home: 'fa-solid fa-house',
  Landmark: 'fa-solid fa-landmark',
  MapPin: 'fa-solid fa-location-dot',
  Flag: 'fa-solid fa-flag',
  Anchor: 'fa-solid fa-anchor',
  Rocket: 'fa-solid fa-rocket',
  Zap: 'fa-solid fa-bolt',
  Flame: 'fa-solid fa-fire',
  Droplets: 'fa-solid fa-droplet',
  Wind: 'fa-solid fa-wind',
  Sun: 'fa-solid fa-sun',
  Moon: 'fa-solid fa-moon',
  Star: 'fa-solid fa-star',
  Cloud: 'fa-solid fa-cloud',
  Snowflake: 'fa-solid fa-snowflake',
  Skull: 'fa-solid fa-skull',
  Heart: 'fa-solid fa-heart',
  Gem: 'fa-solid fa-gem',
  Swords: 'fa-solid fa-shield-halved',
  Crown: 'fa-solid fa-crown',
  Key: 'fa-solid fa-key',
  Book: 'fa-solid fa-book',
  Scroll: 'fa-solid fa-scroll',
  Music: 'fa-solid fa-music',
  Hexagon: 'fa-solid fa-hexagon',
  Shield: 'fa-solid fa-shield-halved',
  Store: 'fa-solid fa-store',
  Sparkles: 'fa-solid fa-wand-magic-sparkles',
  Wrench: 'fa-solid fa-wrench',
};

export const ICON_KEYS = Object.keys(ICON_MAP);
